// Regenerates sw.js with the list of every file to keep offline (run after changing web/).
import { readdirSync, statSync, writeFileSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";
const root = new URL(".", import.meta.url).pathname;
const skip = new Set(["sw.js", "build-sw.mjs", "head.html"]);
const files = [];
const walk = (d) => { for (const f of readdirSync(d)) { const p = join(d, f); if (statSync(p).isDirectory()) walk(p); else if (!skip.has(f) && !f.startsWith(".")) files.push(relative(root, p)); } };
walk(root);
const hash = createHash("sha1"); for (const f of files.sort()) hash.update(f).update(readFileSync(join(root, f)));
const version = hash.digest("hex").slice(0, 10);
writeFileSync(join(root, "sw.js"), `// Generated by build-sw.mjs — offline cache for the whole game.
const CACHE = "lovesim-${version}";
const FILES = ${JSON.stringify(["./", ...files], null, 0)};
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).then((res) => {
    if (res.ok && new URL(e.request.url).origin === location.origin) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); }
    return res;
  })));
});
`);
console.log("sw.js:", files.length, "files, cache", version);
