// Regenerates sw.js with the list of every file to keep offline (run after changing web/).
import { readdirSync, statSync, writeFileSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";
import { createHash } from "node:crypto";
const root = new URL(".", import.meta.url).pathname;
const skip = new Set(["sw.js", "build-sw.mjs", "head.html"]);
// Cache-bust bgm.js in the page so phones never keep an old copy.
const bgmHash = createHash("sha1").update(readFileSync(join(root, "bgm.js"))).digest("hex").slice(0, 8);
const indexPath = join(root, "index.html");
writeFileSync(indexPath, readFileSync(indexPath, "utf8").replace(/src="bgm\.js(\?v=[0-9a-f]*)?"/, `src="bgm.js?v=${bgmHash}"`));
const files = [];
const walk = (d) => { for (const f of readdirSync(d)) { const p = join(d, f); if (statSync(p).isDirectory()) walk(p); else if (!skip.has(f) && !f.startsWith(".")) files.push(relative(root, p)); } };
walk(root);
const hash = createHash("sha1"); for (const f of files.sort()) hash.update(f).update(readFileSync(join(root, f)));
const version = hash.digest("hex").slice(0, 10);
writeFileSync(join(root, "sw.js"), `// Generated by build-sw.mjs — offline cache for the whole game.
const CACHE = "lovesim-${version}";
const FILES = ${JSON.stringify(["./", ...files], null, 0)};
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
// The page and scripts: network first (a new version shows right away), the cache when offline.
// Pictures, music, fonts: cache first (big, rarely change).
self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;
  const fresh = e.request.mode === "navigate" || /\.(html|js|webmanifest)$/.test(url.pathname) || url.pathname.endsWith("/");
  const save = (res) => { if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(e.request, copy)); } return res; };
  // no-cache: always ask the server (GitHub Pages lets browsers keep files 10 min otherwise).
  if (fresh) e.respondWith(fetch(url.href, { cache: "no-cache", credentials: "same-origin" }).then(save).catch(() => caches.match(e.request, { ignoreSearch: true })));
  else e.respondWith(caches.match(e.request, { ignoreSearch: true }).then((hit) => hit || fetch(e.request).then(save)));
});
`);
console.log("sw.js:", files.length, "files, cache", version);
